<div class="login-box">
  <div class="login-logo">
    <?php

    if(isset($this->views->error)) {
        foreach ($this->views->error as $msg) {
            echo "<div style='color:red;'>" . $msg . "</div>"; 
        }
    }
    if(isset($_SESSION["thanhcong"])){
      echo "<div style='color:red;font-size:20px;'>" .$_SESSION["thanhcong"]. "</div>"; 
      unset($_SESSION["thanhcong"]);
    }

?>
    <a href="../../index2.html"><b>Đăng</b>Nhập</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">

    <p class="login-box-msg">Đăng nhập vào tài khoản của bạn</p>

    <form action="" method="post">
      <div class="form-group has-feedback">
        <input type="text" class="form-control" placeholder="Username" name="userlogin" id="userlogin">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        <div style="color: red" id="userlogin1">xin mời bạn nhập tài khoản</div>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password" name="passwordlogin" id="passwordlogin">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        <div style="color: red" id="passwordlogin1">xin mời bạn nhập password</div>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
           <a href="?controller=user&action=register">Đăng ký tài khoản</a>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <input type="submit" value="Đăng nhập" name="dangnhap" id="dangnhap">
        </div>
        <!-- /.col -->
      </div>
    </form>

    <div class="social-auth-links text-center">
      <p>- Hoặc -</p>
      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
        Facebook</a>
      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
        Google+</a>
    </div>
    <!-- /.social-auth-links -->

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

