   <div class="box">
          
            <!-- /.box-header -->
            <div class="box-body">
               <a href="?controller=danhsach&action=themdanhmuc" style="font-size: 20px;">+Thêm Danh mục</a>
                <div>
                <form method="post" action="">
                 Tên danh mục: <input type="text" name="danhmuc" placeholder="Tìm với danh mục" size="30px;">
                 <button name="timkiem" type="submit" class="btn btn-danger btn-sm">Tìm kiếm</button>
               </form>
               </div>
            <?php
              if(isset($_SESSION["themdm"])){
                echo "<div style='color:green;font-size:20px;'>" .$_SESSION["themdm"]. "</div>"; 
                unset($_SESSION["themdm"]);
              }

               if(isset($_SESSION["suadm"])){
                echo "<div style='color:green;font-size:20px;'>" .$_SESSION["suadm"]. "</div>"; 
                unset($_SESSION["suadm"]);
              }
            ?>
               <div></div>
              <table id="example1" class="table table-bordered table-striped">
             
                <tr>
                  <th>ID</th>
                  <th>Tên danh mục</th>
                  <th>Chỉnh sửa</th>
                  <th>Xóa</th>
                </tr>
               
          <?php
          if(isset($_POST["timkiem"])){
            foreach ($this->views_dm as $key => $value1) {
          ?>
           <tr>
                  <td><?= $value1["id"] ?></td>
                  <td><?= $value1["ten_the_loai"] ?></td>             
                  <td><a href="?controller=danhsach&action=suadanhmuc&id=<?=$value1["id"]?>">Chỉnh sửa</a></td>
                  <td><a href="?controller=danhsach&action=deletedm&id=<?=$value1["id"]?>" onclick="return xoa()">Xóa</a></td>
                </tr>
          <?php
          }}else{
          foreach($this->views->list_danhmuc as $value){ 
       
            ?>
                <tr>
                  <td><?= $value["id"] ?></td>
                  <td><?= $value["ten_the_loai"] ?></td>             
                  <td><a href="?controller=danhsach&action=suadanhmuc&id=<?=$value["id"]?>">Chỉnh sửa</a></td>
                  <td><a href="?controller=danhsach&action=deletedm&id=<?=$value["id"]?>" onclick="return xoa()">Xóa</a></td>
                </tr>
          <?php }} ?>
             
               <tr>
                  <th>ID</th>
                  <th>Tên danh mục</th>
                  <th>Chỉnh sửa</th>
                  <th>Xóa</th>
                </tr>
           
              </table>
            </div>
            <!-- /.box-body -->
          </div>
            <div class="pagination" style="float: right;margin-right: 40px;width: 115px;">
           <?php 
            // PHẦN HIỂN THỊ PHÂN TRANG
            // BƯỚC 7: HIỂN THỊ PHÂN TRANG
 
            // nếu current_page > 1 và total_page > 1 mới hiển thị nút prev
            if ($this->views->current_pages > 1 && $this->views->total_pages > 1){
                echo '<a href="?controller=danhsach&action=danhmucsach&page='.($this->views->current_pages-1).'" style="font-size:16px;">Prev | </a>';
            }
 
            // Lặp khoảng giữa
            for ($i = 1; $i <= $this->views->total_pages; $i++){
                // Nếu là trang hiện tại thì hiển thị thẻ span
                // ngược lại hiển thị thẻ a
                if ($i == $this->views->current_pages){
                    echo '<span style="font-size:16px;">'.$i.' |</span>  ';
                }
                else{
                    echo '<a href="?controller=danhsach&action=danhmucsach&page='.$i.'" style="font-size:16px;">'.$i.' |</a> ';
                }
            }
 
            // nếu current_page < $total_page và total_page > 1 mới hiển thị nút prev
            if ($this->views->current_pages < $this->views->total_pages && $this->views->total_pages > 1){
                echo '<a href="?controller=danhsach&action=danhmucsach&page='.($this->views->current_pages+1).'" style="font-size:16px;">Next</a> ';
            }
           ?>
        </div>


