<div class="box box-info">

            <div class="box-header with-border">
              <h3 class="box-title">Thêm sản phẩm</h3>
            </div>
        
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
              <div class="box-body">

              	<div class="form-group">
                  <label for="txt_hoten" class="col-sm-2 control-label" >Tên sách</label>

                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_tensach" placeholder="Tên sách" name="txt_tensach">
                  </div>
                </div>

                <div class="form-group">
                  <label for="txt_username" class="col-sm-2 control-label">Năm xuất bản</label>

                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_namxuatban"  placeholder="Năm xuất bản" name="txt_namxuatban">
                  </div>
                </div>

                <div class="form-group">
                  <label for="txt_email" class="col-sm-2 control-label">Trọng lượng</label>

                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_trongluong" placeholder="Trọng lượng" name="txt_trongluong">
                  </div> 
                </div>
                <div class="form-group">
                  <label for="txt_passwd" class="col-sm-2 control-label">Kích thước</label>

                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_kichthuoc" placeholder="Kích thước" name="txt_kichthuoc">
                  </div>
                </div>
                <div class="form-group">
                  <label for="txt_ngaysinh" class="col-sm-2 control-label">Số trang</label>

                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_sotrang" name="txt_sotrang" placeholder="Số trạng">
                  </div>
                </div>
                 <div class="form-group">
                  <label for="txt_gioitinh" class="col-sm-2 control-label">Hình thức</label>

                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_hinhthuc" name="txt_hinhthuc" placeholder="Hình thức">
                  </div>
                </div>
                 <div class="form-group">
                  <label for="txt_dienthoai" class="col-sm-2 control-label">Ngôn ngữ</label>

                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_ngonngu" name="txt_ngonngu" placeholder="Ngôn ngữ">
                  </div>
                </div>
                 <div class="form-group">
                  <label for="txt_diachi" class="col-sm-2 control-label">Giới thiệu</label>

                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_gioithieu" name="txt_gioithieu" placeholder="Giới thiệu">
                  </div>
                </div>
                <div class="form-group">
                  <label for="slx_nhomtk" class="col-sm-2 control-label">Giá gốc</label>

                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_giagoc" name="txt_giagoc" placeholder="Giá gốc">
                  </div>
                </div>
                <div class="form-group">
                  <label for="slx_nhomtk" class="col-sm-2 control-label">Giá bán</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_giaban" name="txt_giaban" placeholder="Giá bán">
                  </div>
                </div> 
                  <div class="form-group">
                  <label for="slx_nhomtk" class="col-sm-2 control-label">Hình ảnh</label>
                  <div class="col-sm-10">
                    <input type="file" class="form-control" id="txt_hinhanh" name="txt_hinhanh" placeholder="Hình ảnh">
                  </div>
                </div> 
                  <div class="form-group">
                  <label for="slx_nhomtk" class="col-sm-2 control-label">Trạng thái</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_trangthai" name="txt_trangthai" placeholder="Trạng thái">
                  </div>
                </div> 
                  <div class="form-group">
                  <label for="slx_nhomtk" class="col-sm-2 control-label">Khuyến mãi</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_khuyenmai" name="txt_khuyenmai" placeholder="Khuyến mãi">
                  </div>
                </div> 
                  <div class="form-group">
                  <label for="slx_nhomtk" class="col-sm-2 control-label">Đánh giá</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_danhgia" name="txt_danhgia" placeholder="Đánh giá">
                  </div>
                </div> 
                  <div class="form-group">
                  <label for="slx_nhomtk" class="col-sm-2 control-label">Tác giả</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_tacgia" name="txt_tacgia" placeholder="Tác giả">
                  </div>
                </div> 
                  <div class="form-group">
                  <label for="slx_nhomtk" class="col-sm-2 control-label">Nhà cung cấp</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_nhacungcap" name="txt_nhacungcap" placeholder="Nhà cung cấp">
                  </div>
                </div> 
                  <div class="form-group">
                  <label for="slx_nhomtk" class="col-sm-2 control-label">Nhà xuất bản</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_nhaxuatban" name="txt_nhaxuatban" placeholder="Nhà xuất bản">
                  </div>
                </div> 
                  <div class="form-group">
                  <label for="slx_nhomtk" class="col-sm-2 control-label">Mã nhân viên</label>
                  <div class="col-sm-10">
                     <select name="slx_manv" id="slx_manv" class="form-control">
                  <option>== Chọn nhóm tài khoản ==</option>
                    <?php
                      if(isset($this->views->list_idnv1)){
                        foreach ($this->views->list_idnv1 as $value) {
                  ?>
                       <option value="<?=$value["id"]?>"><?=$value["ho_ten"]?></option>       
                  <?php         
                        }}
                  ?>
                </select>
                  </div>
                </div> 
                  <div class="form-group">
                  <label for="slx_nhomtk" class="col-sm-2 control-label">Mã tài khoản</label>
                  <div class="col-sm-10">
                     <select name="slx_mataikhoan" id="slx_mataikhoan" class="form-control">
                  <option>== Chọn nhóm tài khoản ==</option>
                  <?php
                      if(isset($this->views->list_idtk1)){
                        foreach ($this->views->list_idtk1 as $value) {
                  ?>
                       <option value="<?=$value["id"]?>"><?=$value["username"]?></option>       
                  <?php         
                        }}
                  ?>
                </select>
                  </div>
                </div> 
                  <div class="form-group">
                  <label for="slx_nhomtk" class="col-sm-2 control-label">Số lượng</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_soluong" name="txt_soluong" placeholder="Số lượng">
                  </div>
                </div> 
                  <div class="form-group">
                  <label for="slx_nhomtk" class="col-sm-2 control-label">Tên không dấu</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_khongdau" name="txt_khongdau" placeholder="Tên sách không dấu">
                  </div>
                </div> 
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
       
                 <input type="submit" name="add" id="add" value="Thêm sản phẩm" style="float: right;">
                <a href="?controller=danhsach&action=listsanpham">Quay lại</a>
              </div>
              <!-- /.box-footer -->
            </form>
          </div>