<div class="box box-info">
  <?php
if(isset($this->views->error)) {
        foreach ($this->views->error as $msg) {
            echo "<div style='color:red;'>" . $msg . "</div>"; 
        }
    }

    if(isset($this->views->success)) {
        foreach ($this->views->success as $msg) {
            echo "<div style='color:green;'>" . $msg . "</div>"; 
        }
    }
  ?>
            <div class="box-header with-border">
              <h3 class="box-title">Chỉnh sửa tài khoản</h3>
            </div>
            <form class="form-horizontal" method="post" action="">
              <div class="box-body">

              	<div class="form-group">
                  <label for="txt_hoten" class="col-sm-2 control-label" >Họ Tên</label>

                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_hoten" placeholder="Họ tên" name="txt_hoten" value="<?=$this->views->row["ho_ten"]?>">
                  </div>
                </div>

                <div class="form-group">
                  <label for="txt_username" class="col-sm-2 control-label">Username</label>

                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_username"  placeholder="Username" name="txt_username" value="<?=$this->views->row["username"]?>">
                  </div>
                </div>

                <div class="form-group">
                  <label for="txt_email" class="col-sm-2 control-label">Email</label>

                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_email" placeholder="Email" name="txt_email" value="<?=$this->views->row["email"]?>">
                  </div> 
                </div>
                <div class="form-group">
                  <label for="txt_passwd" class="col-sm-2 control-label">Password</label>

                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_passwd" placeholder="Password" name="txt_passwd" value="<?=$this->views->row["password"]?>">
                  </div>
                </div>
                 <div class="form-group">
                  <label for="txt_diachi" class="col-sm-2 control-label">Địa chỉ</label>

                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_diachi" name="txt_diachi" placeholder="địa chỉ" value="<?=$this->views->row["dia_chi"]?>">
                  </div>
                </div>
                <div class="form-group">
                  <label for="slx_nhomtk" class="col-sm-2 control-label">Nhóm tài khoản</label>

                  <div class="col-sm-10">
                     <select name="slx_nhomtk" id="slx_nhomtk" class="form-control">
		              <option value="0">== Chọn nhóm tài khoản ==</option>
		             <?php
                     if(isset($this->views->nhomtk)){
                      foreach ($this->views->nhomtk as $ten_nhom) { ?>

                         <option value="<?=$ten_nhom["id"]?>"><?=$ten_nhom["ten_nhom"]?></option>

                  <?php       
                    }}
                  ?>
		            </select>
                  </div>

                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
       
                <input type="submit" name="update" id="update" value="Chỉnh sửa" style="float: right;">
                <a href="?controller=danhsach&action=danhsachtaikhoan">Quay lại</a>
              </div>
              <!-- /.box-footer -->
            </form>
          </div>