	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!-- ASIDE -->
			<!-- 	<div id="aside" class="col-md-3" style="margin-left: -17px;margin-top: 20px;">
				<div >
				                <div class="banner banner-2">
					<img src="Public/image/img6.jpg" alt="" style="height: 481px;">
				</div>
				<div class="banner banner-2">
					<img src="Public/image/img7.jpg" alt="" style="height: 481px;">
				</div>
			</div>
			</div> -->
				<!-- /ASIDE -->

				<!-- MAIN -->
				<div id="main" class="col-lg-12">
					<!-- store top filter -->
					
					<!-- /store top filter -->
					<div id="store" style="margin-left: 17px;">
						
                       <div class="row"> 
                <h2>Danh sách Bình luận</h2>
             	<?php
                     	 if(isset($_SESSION["duyetcmt"])){
                echo "<div style='color:green;font-size:20px;'>" .$_SESSION["duyetcmt"]. "</div>"; 
                unset($_SESSION["duyetcmt"]);
            }
            ?>
                <table class="table" >
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Username</th>
                            <th>Tiêu đề</th>
                            <th>Bình luận</th>
                            <th>Mã sách</th>
                            <th>Thời gian comment</th>
                            <th>Trạng thái</th>
                            <th>Xét duyệt</th>
                            <th>Xóa</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    $stt = 0; 
                    foreach ($this->views->list_comment as $key => $value) {
                    	$stt++;
                     ?>
                        <tr>
                            <td><?= $value["id"] ?></td>
                            <td><?= $value["username"] ?></td>
                            <td><?= $value["tieu_de"] ?></td>
                            <td><?= $value["comment"] ?></td>
                            <td><?= $value["id_sach"] ?></td>
                            <td><?= $value["thoi_gian_bl"] ?></td>
                            <td>
                            	<select name="duyetcmt">
                            		<?php if($value["trang_thai"] == 'Y'){ ?>
                            		<option value="Y">Duyệt</option>
                            	<?php } else { ?>
                            		<option value="N">Chưa duyệt</option>
                            	<?php } ?>
                            	</select>
                            </td>
                            <td><a href="?controller=trangphu-sanpham&action=duyetcmt&id=<?=$value["id"]?>" style="color: blue;">Xét duyệt</a></td>
                            <td><a href="#" style="color: green;">Xóa</a></td>                     
                        </tr>
                        <?php } ?>
                    </tbody>
                     <thead>
                        <tr>
                           <th>ID</th>
                            <th>Username</th>
                            <th>Tiêu đề</th>
                            <th>Bình luận</th>
                            <th>Mã sách</th>
                            <th>Thời gian comment</th>
                            <th>Trạng thái</th>
                             <th>Xét duyệt</th>
                            <th>Xóa</th>
                        </tr>
                    </thead>
                </table>
      
            </div>
			
					<!-- /STORE -->
					<!-- store bottom filter -->
					<div class="store-filter clearfix">
						          <div class="pagination" style="float: right;margin-right: -150px;width: 300px;">
           <?php 
            // PHẦN HIỂN THỊ PHÂN TRANG
            // BƯỚC 7: HIỂN THỊ PHÂN TRANG
 
            // nếu current_page > 1 và total_page > 1 mới hiển thị nút prev
            if ($this->views->current_pages > 1 && $this->views->total_pages > 1){
                echo '<a href="?controller=trangphu-sanpham&action=danhsachcmt&page='.($this->views->current_pages-1).'" style="font-size:16px;color:blue;">Prev | </a>';
            }
 
            // Lặp khoảng giữa
            for ($i = 1; $i <= $this->views->total_pages; $i++){
                // Nếu là trang hiện tại thì hiển thị thẻ span
                // ngược lại hiển thị thẻ a
                if ($i == $this->views->current_pages){
                    echo '<span style="font-size:16px;color:red;">'.$i.' |</span>  ';
                }
                else{
                    echo '<a href="?controller=trangphu-sanpham&action=danhsachcmt&page='.$i.'" style="font-size:16px;color:blue;">'.$i.' |</a> ';
                }
            }
 
            // nếu current_page < $total_page và total_page > 1 mới hiển thị nút prev
            if ($this->views->current_pages < $this->views->total_pages && $this->views->total_pages > 1){
                echo '<a href="?controller=trangphu-sanpham&action=danhsachcmt&page='.($this->views->current_pages+1).'" style="font-size:16px;color:blue;">Next</a> ';
            }
           ?>
        </div>


					</div>
					</div>
					<!-- /store bottom filter -->
				</div>
				<!-- /MAIN -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
