	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!-- ASIDE -->
			<!-- 	<div id="aside" class="col-md-3" style="margin-left: -17px;margin-top: 20px;">
				<div >
				                <div class="banner banner-2">
					<img src="Public/image/img6.jpg" alt="" style="height: 481px;">
				</div>
				<div class="banner banner-2">
					<img src="Public/image/img7.jpg" alt="" style="height: 481px;">
				</div>
			</div>
			</div> -->
				<!-- /ASIDE -->

				<!-- MAIN -->
				<div id="main" class="col-lg-12">
					<!-- store top filter -->
					<div class="store-filter clearfix">
						<div class="pull-right">
							<ul class="store-pages">
								<li><span class="text-uppercase">Page:</span></li>
								<li class="active">1</li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#"><i class="fa fa-caret-right"></i></a></li>
							</ul>
						</div>
					</div>
					<!-- /store top filter -->
					<div id="store" style="margin-left: 17px;">
						<div class="container col-lg-7" style="margin-left: 240px;">
                       <div class="row"> 
                <h2>Bình luận</h2>
                <form method="post" action="">
                <table class="table" >
                    <thead>
                        <tr>
                            <th>Mã bình luận</th>
                            <th>Duyện bình luận</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><?= $this->views->cmt["id"] ?></td>
                            <td>
                            	<select name="trangthai">
                            		<option value="Y">Duyệt</option>
                            		<option value="N">Chưa duyệt</option>
                            	</select>
                            </td>                     
                        </tr>
                        <tr>
                        	<td></td>
                        	<td><input type="submit" name="duyet" id="duyet" value="Duyệt Bình luận"></td>
                        </tr>


                    </tbody>
                     <thead>
                        <tr>
                          <th>Mã bình luận</th>
                            <th>Duyện bình luận</th>
                        </tr>
                    </thead>
                </table>
            </form>
            </div>
					</div>
					<!-- /STORE -->
					<!-- store bottom filter -->
					<div class="store-filter clearfix">
						<div class="pull-right">
						
							<ul class="store-pages">
								<li><span class="text-uppercase">Page:</span></li>
								<li class="active">1</li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#"><i class="fa fa-caret-right"></i></a></li>
							</ul>
						</div>
					</div>
					</div>
					<!-- /store bottom filter -->
				</div>
				<!-- /MAIN -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
