<!-- Horizontal Form -->
          <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">THÊM TÀI KHOẢN</h3>
            </div>

            <?php 
        	foreach($dataView['errors'] as $msg ){
        		echo '<div class="alert alert-danger">'.$msg.'</div>';
        	}

			foreach($dataView['success'] as $msg ){
        		echo '<div class="alert alert-success">'.$msg.'</div>';
        	}
 
            ?>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" action="" method="post">
              <div class="box-body">
				<div class="form-group">
                  <label for="txt_ho_ten" class="col-sm-2 control-label">Họ Tên</label>

                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_ho_ten"  name="txt_ho_ten" placeholder="Họ tên">
                  </div>
                </div>
                <div class="form-group">
                  <label for="txt_username" class="col-sm-2 control-label">Username</label>

                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="txt_username"  name="txt_username" placeholder="Username">
                  </div>
                </div>

                <div class="form-group">
                  <label for="txt_email" class="col-sm-2 control-label">Email</label>
                  <div class="col-sm-10">
                    <input type="email" class="form-control" 
                    id="txt_email" name="txt_email" placeholder="Email">
                  </div>
                </div>

                <div class="form-group">
                  <label for="txt_passwd" class="col-sm-2 control-label">Password</label>

                  <div class="col-sm-10">
                    <input type="password" class="form-control" id="txt_passwd" placeholder="Password" name="txt_passwd">
                  </div>
                </div>


                <div class="form-group">
                  <label for="slx_nhomtk" class="col-sm-2 control-label">Nhóm tài khoản</label>

                  <div class="col-sm-10">
                    
                  	<select name="slx_nhomtk" id="slx_nhomtk" class="form-control">
		              <option>== Chọn nhóm tài khoản ==</option>
		                <?php 
		                  if(is_array($dataView['listNhomTK'])){
		                      foreach($dataView['listNhomTK'] as $id=>$ten_nhom){
		                        echo "<option value='$id'>$ten_nhom</option>";    
		                      }
		                  }
		                ?>
		          </select>


                  </div>
                </div>

               
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <a href="?controller=admin-user">Back</a>
                <button type="submit" class="btn btn-info pull-right">Save</button>
              </div>
              <!-- /.box-footer -->
            </form>
          </div>