 <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Danh sách tài khoản
        <small>it all starts here</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Examples</a></li>
        <li class="active">Blank page</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Title</h3>



          <div class="box-tools pull-right">
            <a href="?controller=admin-user&action=add">Thêm mới </a>
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
        <form method="get" action="">
          <input type="hidden" name="controller" value="admin-user">
          <input type="hidden" name="action" value="index">
          <input type="text" name="search_hoten" placeholder="Họ tên" 
                value="<?php echo @$_GET['search_hoten'];?>">

          <input type="text" name="search_username" placeholder="Username"
                  value="<?php echo @$_GET['search_username'];?>">

          <input type="text" name="search_email" placeholder="Email"
                  value="<?php echo @$_GET['search_email'];?>">

          <select name="search_nhomtk">
              <option>== Chọn nhóm tài khoản ==</option>
                <?php 
                  if(is_array($dataView['listNhomTK'])){
                      foreach($dataView['listNhomTK'] as $id=>$ten_nhom){
                        $selected = '';
                        if(isset($_GET['search_nhomtk']) && $_GET['search_nhomtk']==$id)
                            $selected = ' selected ';

                        echo "<option value='$id' $selected>$ten_nhom</option>";    
                      }
                  }
                ?>

          </select>




          
          <input type="submit" value="Search">
          <a href="?controller=admin-user">Clear</a>

        </form>

         
        <?php
            // echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
            //   print_r($dataView);
            // echo '</pre>'; 

            if(!is_array($dataView['listUser'])){
              echo '<div class="alert alert-danger alert-dismissible">';
              echo $dataView['listUser'];
              echo '</div>'; 
              goto end_action;
            }

            if(count($dataView['listUser']) ==0){
              echo '<div class="alert alert-warning alert-dismissible">
                      Không có dữ liệu.
                    </div>';
              goto end_action;      
            }

            // In bảng user CreateLinkSortTable($column)
            echo "<table class='table table-bordered'>
                  <tr>
                    <td><a href='".CreateLinkSortTable('id')."'>ID</a></td>
                    <td><a href='".CreateLinkSortTable('ho_ten')."'>Họ tên</a></td>
                    <td><a href='".CreateLinkSortTable('username')."'>Username</a></td>
                    <td><a href='".CreateLinkSortTable('email')."'>Email</a></td>
                    <td><a href='".CreateLinkSortTable('id_nhom_TK')."'>Nhóm TK</a></td>
                  </tr>
                 ";

            foreach($dataView['listUser'] as $row){

              echo "
                  <tr>
                    <td>{$row['id']}</td>
                    <td>{$row['ho_ten']}</td>
                    <td>{$row['username']}</td>
                    <td>{$row['email']}</td>
                    <td>{$row['ten_nhom']}</td>
                  </tr>
                 "; 
            }
            echo "</table>";  

            if($dataView['tong_so_trang']>1){
              // in ra các số trang
              echo '<div class="box-footer clearfix">
              <ul class="pagination pagination-sm no-margin pull-right">';

              // Tạo chuối link 
              $url ='?';
              foreach($_GET as $name =>$val){
                  if($name == 'page') continue;

                  if($url !='?')
                    $url .='&';
                  $url .= $name .'='.$val;
                }


                for($i = 1; $i<= $dataView['tong_so_trang']; $i++){
                   $url_page =  $url.'&page=' .$i;
                  echo '<li><a href="'. $url_page.'">'.$i.'</a></li>';
                }

                // <li><a href="#">&laquo;</a></li>
                // <li><a href="#">1</a></li>
                // <li><a href="#">2</a></li>
                // <li><a href="#">3</a></li>
                // <li><a href="#">&raquo;</a></li>

            echo '</ul>
                    </div>';

            }


        end_action:    
        ?>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          Footer
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box --> 
    </section>
    <!-- /.content -->